# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fdb8e612854bd65ff979b825c01f04ebb1cb328b231010c11b8c3ac6186989f9d2fb7909004f95beacf5271aa94375ad35e071ba452f5be87255b589491cd07

test:
  secret_key_base: 1ecacd66c3af38b937da553f8867f184c7021d05075acf84c9ee93cf6a98f0262a2b1431004499149c82834849a1835dfaf4ea4a676cd795dc752933e858a5a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
